### PR TITLE
Bump healthcheck to 60 seconds - some svcs take longer than 30 to start up

### PR DESCRIPTION
**Pull request by paololim**

### CODE REVIEW

**Comment by mbryzek** [comment]
any idea why services take so long to startup?

worried this will become a big problem for us

**Comment by paololim** [comment]
from what I can tell, the following add a few seconds to startup time: any dependency-injected class where we define non-lazy vals that have overhead setup (mostly actors and clients)

**Comment by mbryzek** [comment]
lgtm

**Comment by chrhicks** [comment]
@paololim what was the reason for closing? is there another solution ?

**Comment by paololim** [comment]
@chrhicks are you still encountering this issue?

there were issues on startup for postgresql dockerfiles, which we fixed.

**Comment by chrhicks** [comment]
@paololim Yes.. everyday :)

**Pull request closed without merging**
